# models.py
from django.db import models

class cancerdb(models.Model):
    m_Patient_Id = models.IntegerField(primary_key=True)
    m_Age = models.IntegerField()
    m_Gender = models.CharField(max_length=10)
    m_BMI = models.FloatField()
    m_BSA = models.FloatField()
    m_ECOG = models.CharField(max_length=40)
    m_Substanceabuse = models.CharField(max_length=40)
    m_DiabetesCI = models.CharField(max_length=40)
    m_HeartDiseaseCI = models.CharField(max_length=40)
    m_EjectionFraction = models.FloatField()
    m_Weightloss = models.FloatField()
    m_Haemoglobin = models.FloatField()
    m_WBC = models.FloatField()
    m_ANC = models.FloatField()
    m_PlatletCount = models.FloatField()
    m_Creatininel = models.FloatField()
    m_Creatininec = models.FloatField()
    m_Bilrubin = models.FloatField()
    m_AST = models.FloatField()
    m_Albumin = models.FloatField()
    m_SpO2 = models.FloatField()
    m_Heartrate = models.FloatField()
    m_PriorHospitalization = models.CharField(max_length=20)
    m_BP = models.CharField(max_length=20)
    m_Walking = models.CharField(max_length=20)
    m_Drug = models.CharField(max_length=100)
    m_Chemoagent = models.IntegerField()
    m_Dosingagent = models.CharField(max_length=20)
    m_Setting = models.CharField(max_length=100)
    m_SocialSupport = models.CharField(max_length=20)
    m_DistanceFH = models.CharField(max_length=20)
    m_MentalState = models.CharField(max_length=20)
    m_CancerType = models.CharField(max_length=100)
    m_Gradeg = models.CharField(max_length=100)
    m_StageBurden = models.CharField(max_length=100)
    m_ChemoTolerance = models.CharField(max_length=100)
    m_DuringChemo = models.CharField(max_length=100)
    m_Cycle = models.IntegerField()